image:
  repository: ghcr.io/imansabet/shortlink-platform
  tag: 5675594a72d3c160efb94a6125fe27f92fffa5f5
  pullPolicy: IfNotPresent

metrics:
  serviceMonitor:
    enabled: true
  dashboard:
    enabled: true
