image:
  repository: ghcr.io/imansabet/shortlink-platform
  tag: a850136a25d4bb9727af573196f475e5d8e167fb
  pullPolicy: IfNotPresent

metrics:
  serviceMonitor:
    enabled: true
  dashboard:
    enabled: true
